# Generated by Django 6.0.6 on 2026-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
