# Generated by Django 6.0.6 on 2026-08-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='application',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.CharField(default='Fresher', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(default='Unkown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='salary',
            field=models.CharField(default='Unkown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship')], default='Job', max_length=20),
        ),
    ]
