# Generated by Django 6.0.6 on 2026-08-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_company_name_remove_job_employer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
