# Generated by Django 6.0.6 on 2026-08-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_application_employer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
