# Generated by Django 6.0.6 on 2026-08-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=100, max_length=100, null=True),
        ),
    ]
