# Generated by Django 6.0.7 on 2026-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
