# Generated by Django 6.0.7 on 2026-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('offer_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Offered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
