# Generated by Django 6.0.7 on 2026-08-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_hiringoffer'),
        ('students', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringoffer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_offer', to='students.application'),
        ),
    ]
