# Generated by Django 6.0.7 on 2026-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_hiringoffer_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringoffer',
            name='offer_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hiringoffer',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
