# Generated by Django 6.0.7 on 2026-08-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_alter_hiringoffer_offer_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringoffer',
            name='status',
            field=models.CharField(default='Offered', max_length=20),
        ),
    ]
